application:
  environment: 'prod'
  language: 'en'
  languages:
    en: "English (United States)"
  editor: 'vim'
  temp: '/tmp'
  develop: 'false'
  command: 'about'
  checked: 'false'
  clear: 'false'
  remote:
    user: 'wordpress'
#    password: 'wordpress'
    port: '22'
#    keys:
#      public: '~/.ssh/id_rsa.pub'
#      private: '~/.ssh/id_rsa'
#      passphrase: '~/.ssh/passphrase.txt'
  options:
    learning: true
#    target: wordpressvm.dev
#    uri: miltisite.dev
    generate-inline: false
    generate-chain: false
