services:
  # WordpressConsoleCore Services
  console.chain:
    class: WP\Console\Core\Command\Chain\ChainCommand
    arguments: ['@console.chain_queue', '@console.chain_discovery']
    tags:
      - { name: wordpress.command }
  console.chain_debug:
      class: WP\Console\Core\Command\Chain\ChainDebugCommand
      arguments: ['@console.chain_discovery']
      tags:
        - { name: wordpress.command }
  console.exec:
      class: WP\Console\Core\Command\Exec\ExecCommand
      arguments: ['@console.shell_process']
      tags:
        - { name: wordpress.command }
  console.remote:
      class: Drupal\Console\Core\Utils\Remote
      arguments: ['@console.translator_manager']
  console.shell_process:
      class: WP\Console\Core\Utils\ShellProcess
      arguments: ['@app.root', '@console.translator_manager']
  console.validator:
      class: WP\Console\Utils\Validator
      arguments: ['@console.extension_manager']
#  console.generate_plugin:
#    class: WP\Console\Command\Generate\PluginCommand
#    arguments: ['@console.plugin_generator', '@console.validator', '@app.root', '@console.string_converter', '@http_client', '@console.site']
#    tags:
#      - { name: wordpress.command }
#  console.plugin_generator:
#    class: WP\Console\Generator\PluginGenerator
#    tags:
#      - { name: wordpress.generator }