services:
  # WordpressConsoleCore Services
  console.configuration_manager:
    class: WP\Console\Utils\ConfigurationManager
  console.chain:
    class: WP\Console\Core\Command\Chain\ChainCommand
    arguments: ['@console.chain_queue', '@console.chain_discovery']
    tags:
      - { name: wordpress.command }
  console.chain_debug:
      class: WP\Console\Core\Command\Chain\ChainDebugCommand
      arguments: ['@console.chain_discovery']
      tags:
        - { name: wordpress.command }
  console.chain_discovery:
      class: WP\Console\Utils\ChainDiscovery
      arguments: ['@console.root', '@console.configuration_manager']
  console.chain_queue:
      class: WP\Console\Utils\ChainQueue
  console.exec:
      class: WP\Console\Core\Command\Exec\ExecCommand
      arguments: ['@console.shell_process']
      tags:
        - { name: wordpress.command }
  console.translator_manager:
    class: WP\Console\Utils\TranslatorManager
  console.shell_process:
      class: WP\Console\Utils\ShellProcess
      arguments: ['@app.root', '@console.translator_manager']
  console.string_converter:
        class: WP\Console\Utils\StringConverter
  console.renderer:
      class: WP\Console\Utils\TwigRenderer
      arguments: ['@console.translator_manager', '@console.string_converter']
  # WordpressConsole Commands
  console.about:
    class: WP\Console\Command\AboutCommand
    tags:
      - { name: wordpress.command }