services:
  console.plugin_generator:
    class: WP\Console\Generator\PluginGenerator
    tags:
      - { name: wordpress.generator }
  console.meta_box_generator:
    class: WP\Console\Generator\MetaBoxGenerator
    arguments: ['@console.extension_manager']
    tags:
      - { name: wordpress.generator }
  console.taxonomy_generator:
    class: WP\Console\Generator\TaxonomyGenerator
    arguments: ['@console.extension_manager']
    tags:
      - { name: wordpress.generator }
  console.theme_generator:
    class: WP\Console\Generator\ThemeGenerator
    arguments: ['@console.extension_manager']
    tags:
      - { name: wordpress.generator }